url: https://y7kim.github.io
baseurl: /

# Site settings
title: Безумцы. Ragnarok M&#58 Eternal Love
email: madmansrom@gmail.com
description: "Веселье Безумца. Сайт гильдии Безумцы. Ragnarok M&#58 Eternal Love EU. Рагнарок русский сервер"




# Build settings
markdown: kramdown
permalink: pretty
